### ISSUE TITLE
API Token visible

### ISSUE THREAD

**Issue by jnuvola** [TerribleTurtle/smart_stuff#1]
I was browsing python ST code and noticed this.. You probably don't want to share your API token in public, so please remove it, unless you want random people to control your ST stuff. :)

Edit: also good idea to delete and create a new token after you've removed it from here. 👍 

https://github.com/TerribleTurtle/smart_stuff/blob/c4f413f507ff0bdd6353be668a0ced0fdbd41e5a/smart_stuff.py#L7

**Comment by TerribleTurtle** [comment]
I've removed the token from the code as well as removed the token from use.  Thanks for the heads up,  I'll be more cautious in the future.
